development:
  adapter: mysql2
  database: Kucharka
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: Kucharka_Test
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  database: Kucharka_Production
  username: root
  password:
  host: localhost