development:
  adapter: mysql2
  database: Kucharka
  username: root
  password:
  host: 127.0.0.1

test:
  adapter: mysql2
  database: Kucharka_Test
  username: root
  password:
  host: localhost

production:
  adapter: postgresql
  database: d54frbpm3nj1l7
  username: ctrljzruxyubgr
  password: fkjjx3x75d-BcGAtGPvXETeLB5
  host: ec2-23-21-91-29.compute-1.amazonaws.com
  port: 5432