# coding:utf-8

APP_NAME = "Kuchařka"

# permissions

ROLE_USERS_LIST = 			(1 << 0)
ROLE_USERS_SHOW_SELF =		(1 << 1)
ROLE_USERS_SHOW = 			(1 << 2)
ROLE_USERS_EDIT_SELF = 		(1 << 3)
ROLE_USERS_EDIT = 			(1 << 4)
ROLE_USERS_EDIT_ROLE = 		(1 << 5)
ROLE_USERS_CREATE = 		(1 << 6)
ROLE_USERS_DESTROY_SELF = 	(1 << 7)
ROLE_USERS_DESTROY = 		(1 << 8)

ROLE_RECIPES_EDIT_SELF = 	(1 << 9)
ROLE_RECIPES_EDIT = 		(1 << 10)
ROLE_RECIPES_CREATE_SELF =	(1 << 11)
ROLE_RECIPES_CREATE = 		(1 << 12)
ROLE_RECIPES_DESTROY_SELF = (1 << 13)
ROLE_RECIPES_DESTROY = 		(1 << 14)

ROLE_ARTICLES_EDIT_SELF = 		(1 << 15)
ROLE_ARTICLES_EDIT = 			(1 << 16)
ROLE_ARTICLES_CREATE_SELF =		(1 << 17)
ROLE_ARTICLES_CREATE = 			(1 << 18)
ROLE_ARTICLES_DESTROY_SELF = 	(1 << 19)
ROLE_ARTICLES_DESTROY = 		(1 << 20)

ROLE_COMMENT_SELF	= 		(1 << 21)
ROLE_COMMENT_EDIT_SELF =	(1 << 22)
ROLE_COMMENT_EDIT =			(1 << 23)
ROLE_COMMENT_DELETE_SELF =	(1 << 24)
ROLE_COMMENT_DELETE =		(1 << 25)

ROLE_MARK_CREATE =		(1 << 26)
ROLE_MARK_EDIT_SELF =	(1 << 27)
ROLE_MARK_EDIT =		(1 << 28)
ROLE_MARK_DELETE_SELF =	(1 << 29)
ROLE_MARK_DELETE =		(1 << 30)

ROLE_CATEGORY_INGREDIENCE_CREATE = 	(1 << 31)
ROLE_CATEGORY_INGREDIENCE_EDIT = 	(1 << 32)
ROLE_CATEGORY_INGREDIENCE_DELETE = 	(1 << 33)
ROLE_CATEGORY_RECIPE_CREATE = 	(1 << 34)
ROLE_CATEGORY_RECIPE_EDIT = 	(1 << 35)
ROLE_CATEGORY_RECIPE_DELETE = 	(1 << 36)

#other