---
development:
  cloud_name: deaz43406
  api_key: '898858572865222'
  api_secret: knkqAzzmSU8ROWU9mOGRqXNepXc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: deaz43406
  api_key: '898858572865222'
  api_secret: knkqAzzmSU8ROWU9mOGRqXNepXc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: deaz43406
  api_key: '898858572865222'
  api_secret: knkqAzzmSU8ROWU9mOGRqXNepXc
  enhance_image_tag: true
  static_image_support: false
